// ==UserScript==
// @name         FR Coliseum Enemy Map
// @namespace    https://tampermonkey.net/
// @version      1.0
// @description  Enemy Map for FR Coliseum Tracker
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    window.venueEnemyMap = {
        "training_fields": ["Amaranth Moth","Bluelight Chipskink","Brown-Spotted Mith","Bumble","Ceanothus Brawler","Chipskink","Coral Carpenter","Crimson Emperor","Dark Sparrowmouse","Deaths-Head Stag","Ember Mouse","Emerald Webwing","Frosted Pocketmouse","Glowing Pocket Mouse","Leafy Moth","Luna Mith","Mith Bruiser","Primrose Mith","Ragepuff","Ruby Webwing","Satin Pocketmouse","Silky Webwing","Sweetpuff","Webwing Alpha","Yellow Sparrowmouse"],
        "woodland_border": ["Aurelian Porcupine","Autumn Dryad","Bamboo Phytocat","Basilisk","Blooming Strangler","Bluefin Charger","Clown Charger","Cockatrice","Coral Basilisk","Dryad","Featherfoot Spingy","Flying Fawn","Glorious Dayjar","Greenroot Janustrap","Grouse Basilisk","Janustrap","Moonglow Nightjar","Sakura Owl","Scarlet-Crested Woodoon","Spongy Spingy","Spring Glade Lord","Strangler","Trumpet Porcupine","Velvet Fawn","Wildwood Owl"],
        "scorched_forest": ["Augite Protector","Moss-Covered Golem","Banded Owlcat","Centaur Archer","Steam Gyre","Wintermane Bowman","Crowned Bonepriest","Extinguished Jackalope","Painted Centaur","Rambra","Smoke Gyre","Red-Winged Owlcat","Searing Jackalope","Umberhorn Qiriq","Wintermane Spearman","Zeeba","Clown Charger"],
        "boneyard": ["Bearded Shrieker","Bloodfang Hunter","Bloodfang Watcher","Bonebeetle","Boneblade Knight","Bonepicker Archivist","Boneseeker","Boneyard Omen","Boneyard Patroller","Carcass Custodian","Corven Scribe","Corvid Convergence","Hissing Foulscale","Infected Scavenger","Isopuppy","Murder Cage","Oilslick Cockatrice","Ossein Scavenger","Ridgespine Streak","Sisyphus Beetle","Skeletal Streak","Spinal Sorcerer","Spinesword Warden","Steelscale Isopuppy","Sunbleached Foulscale"],
        "sandswept_delta": ["Buff Dunerunner","Carmine Serthis","Charcoal Kitsune","Desert Strangler","Dunerunner","Dusk Fuiran","Fan Scorpion","Fennec Kitsune","Fuiran","Gaboon Viperpillar","Greatshell","Iridescent Scaleback","Masked Gryphon","Nightsky Fuiran","Opheodrys Serthis","Peacock Scorpion","Prickly Strangler","Redtail Gryphon","Sanddrift Fuiran","Scaleback","Serthis Alchemist","Serthis Potionmaster","Shadow Serpent","Shattered Serpent","Storm Seeker"],
        "silk-strewn_wreckage": ["Midnight Lantern","Moth Keeper","Assassin Bug","Colony Killer","Blue Hamble","Catercroak","Climbing Catercroak","Fire Grub Swarm","Flighted Molecricket","Glow Worm Swarm","Hornworm Viperpillar","Illumination Crecko","Jelly Jewel","Maple Bagwitch","Mith Loremaster","Mith Spellstealer","Nightsong Bard","Regal Silkmith","Silkmith","Roving Jelly Jewel","Scarlet Hamble","Shy Bagwitch","Striped Crecko","Sunset Buttersnake","Velvet Buttersnake"],
        "blooming_grove": ["Flowering Pohip","Mossy Pohip","Alstroemeria Fox","Myosotis Fox","Aspen Gall Dryad","Barkskin Watcher","Venomtooth Pilco","Buttercup Strangler","Rosaline Strangler","Five-Toed Pilco","Flora Cerdae","Frostbite Dryad","Ruffletail Tadhop","Sunbeam Dryad","Fungi Sage","Grove Piper","Lilium Floron","Petalmane Floron","Maned Cerdae","White Rot Deer","Moonlight Fungi","Travelling Garden","Palefoot Tadhop","Spotted Faun","Terra Tortoise"],
        "forgotten_cave": ["Burrow Bear","Dire Claw","Ancient Fungus","Dwarf Truffle","Runic Bat","Bell Goat","Blue Dragon Snail","Crimson Reef Snail","Deepmine Aardvark","Blueband Duelist","Peacevine Aardvark","Bramble Guardian","Cave Lantern","Centaur Berserker","Cursed Bat","Citrine Jewel","Emerald Jewel","Venomblade Assassin","Corpse Cleaner","Creeping Cluster","Parasitic Fungus","Djamor Bat","Swiftfoot Slayer","Ostreatus Bat","Polarized Bell Goat"],
        "bamboo_waterfall": ["Cloudrider","Thundercloud Herald","Baku","Dream Eater","Blacktalon Striker","Blazewing Croaker","Warbletongue Croaker","Calico Felislug","Dart-Tail Cockatrice","Golden Cockatrice","Fungalhoof Cerdae","Ethereal Trickster","Trick-of-the-Light","Gale Wolf","Mantled Foo","Raptorik Warrior","Red-Breasted Hainu","Hainu","Reedhollow Traveller","Talonok Mistwatcher","Tengu","Wandering Surge Priest","Tigerblood Foo","Tuxedo Felislug","Umbra Wolf"],
        "thunderhead_savanna": ["Rockback Charger","Thunderstomp","Ampelope","Starry Ampelope","Condorwing Champion","Falconclaw Warrior","Coursing Skira","Grassland Skira","Dire Vulture","Flesh Forager","Dustfeather Sphinx","Magpie Sphinx","Golden Lionsnake","Roving Lionsnake","Greattusk","Pale Greattusk","Heckling Hydrena","Rabid Grinfin","King Quillrunner","Quillrunner","Plainstrider Bard","Wintermane Minstrel","Raptorik Herder","Raptorik Wanderer","Roundhorn Rager"],
        "redrock": ["Deeprealm Hunter","Spiney Whale","Coast Charger","Surf Strider","Coastline Sawbeak","Dainty Wavehopper","Daydream Puffer","Green-Breasted Sawbeak","Highfin Sea Serpent","Igueel Matriarch","Leopard Coralclimber","Maren Defender","Maren Spearmaiden","Maren Sorceress","Redfin Wavespinner","Mirage Puffer","Mottled Sea Serpent","Murkbottom Gull","Tradewinds Gull","Noxious Coralclimber","Oceansurf Magus","Waveswell Sorcerer","Riptide Clipper","Sandshore Snipper","Toxic Igueel"],
        "waterway": ["Ghostly Rat Lord","Rat King","Blueridge Greatshell","Brown River Flight","Grey River Flight","Rainbow Sprite","Crested River Flight","Goldfin River Flight","Cumulus Seal","Dappled Seal","Everglade Lasher","Greater Sandstrike","Fanrat","Silky Fanrat","Giant White Toridae","Sewer Toridae","Granite Thresher","Shale Thresher","Maren Currentfinder","Maren Shark Hunter","Noggle","Sunset Lasher","Radioactive Slime","River Muck","Scaleside Noggle"],
        "arena": ["Featherback Boar","Undying Featherback","Armored Greatowl","Ashmane Chimera","Bengal Chimera","Boran Veteran","Spellwall Boran","Celestial Antelope","Silver Springbok","Charcoal Sprangyroo","Chimera","Double-Tailed Warcat","Warcat Protector","Goldenplains Poodle Mith","Greenwing Razorclaw","Hulking Greatowl","Longneck Gladiator","Longneck Scrapper","Longneck Interloper","Longneck Magi","Longneck Mender","Longneck Skirmisher","Marshland Poodle Mith","Raptorik Bladedancer","Raptorik Ringmaster"],
        "volcanic_vents": ["Hydra","Tunnel Hydra","Armored Duskflapper","Spectral Duskflapper","Ashscale Ophiotaurus","Ophiotaurus","Ashspine Widow","Flamescale Spearman","Basalt Vent Hop","Chillwind Harpy","Fiendcat","Dreadram","Ghost Manticore","Firebelly Weaver","Firemane Manticore","Ultraram","Flamerest Fiendcat","Stormcloud Harpy","Flamescale Illusionist","Flamescale Lancer","Flamescale Venomcaster","Ignited Imp","Nightfall Imp","Magma Runner","Serthis Archivist"],
        "rainsong_jungle": ["Goldenbeast","Overcharged Silverbeast","Barkback Boar","Deadwood Boar","Hippocampus","Clown Hippocampus","King Parda","Parda","Petal Jumper","Budwing Morpho","Proto Manticore","Manticore Screamer","Ultramel Amphithere","Ringlet Amphithere","Zalis","Paradise Zalis"],
        "boreal_wood": ["Coarsefur Yeti","Auburn Woolly Walrus","Woolly Walrus","Black Wolf","Winter Wolf","Bramblecrown Stoat","Pebblehide Stoat","Bullephant","Mammophant","Poultrygeist","Snowfall Elk","Deadwood Strangler","Frosttangle Strangler","Elk","Glassbound Gustvul","Glassbound Solarvul","Hoarfrost Mauler","Longneck Hunter","Longneck Wanderer","Maned Rasa","Squall Rasa","Permafrost Impaler","Nochnyr","Woodland Turkey","Snowy Owlynx"],
        "crystalspine_pools": ["Crystalhide Jester","Hawksbill Goliath","Almandine Sturgeon","Amber Gulper","Windcarve Fugitive","Apatite Fisher","Rhodochrosite Crane","Arctic Hippalectryon","Hippalectryon","Chalcedony Snipper","Moonbeam Crayfish","Clearwater Oracle","Maren Warlock","Crystalplate Stinger","Sparkling Stinger","Stonewatch Prince"],
        "harpys_roost": ["Crowned Roc","Roc","Blue Tang Hippogriff","Cardinal Hippogriff","Cloud Dancer","Mesacliff Assassin","Windcarve Bladedancer","Stonewatch Harpy","Sunspot Clouddancer","Blue Moon Aviar","Renegade Aviar","Dodo","Fallen Streak","Brush Dodo","Hooded Dodo","Masked Harpy","Death Seeker","Storm Seeker","Windcarve Harpy","Mesacliff Harpy","Snow Streak"],"ghostlight_ruins": ["Disoriented Spirit","Malevolent Spirit","Aer Phantom","Lux Spectre","Otherworldly Aura","Carrioncorn","Greybeak Reaper","Nightmare","Tengu Caller","Infestation Hound","Longneck Medium","Wraith Hound","Longneck Scholar","Pronghorn Stomper","Tatterwing Carcass","Somber Spirit","Shatterbone Vulture","Pronghorn Hunter"],
        "mire": ["Molten Wartoad","Wartoad","Acid Ant","Armored Colony","Fungal Garden","Blackwing Croaker","Brilliant Psywurm","Common Podid","Southmarsh Podid","Furry Fiddle","Muckbottom Catfish","Heartred Croaker","Ink Ant","Lion's Mane Seeker","Whisper","Marsh Kelpie","Mistwatch Shellion","Mossy Cerdae","Poisonous Toridae","Scythe Kamaitachi","Venomous Toridae","Psywurm","Shellion","Sickle Kamaitachi","Salve Kamaitachi"],
        "kelp_beds": ["Mantarune","Wave Sweeper","Abyss Striker","Cloud Chaser","Blue-Footed Eggull","Eggull","Corrosive Depin","Maren Warrior","Golden Porpoise","Maren Wavesinger","Kelp Caretaker","Kelp Tender","Jeweled Octoflyer","Maren Ambusher","Mammertee","Maren Fisher","Maren Seahunter","Maren Harvester","Maren Scout","Depin","Octoflyer","Relic Eel","Ruche Slug","Ruched Sojourner","Seastar"],
        "golem_workshop": ["Frost Delver","Stone Borer","Copperplate Longmech","Gearspring Pocketmouse","Geartoggle Smith","Jelly Drone","Longmech","Mechanical Destroyer","Robotic Tender","Tribeam Hunter","Tribeam Lurker","War Smith","Wind-Up Pocketmouse","Workshop Monitor","Black Iron Creeper","Coppercoil Creeper","Chromefeather Lookout","Sentry Squawker","Clattercog Engineer","Monkey Wrench","Construction Mith","Sentinel Mith","Steelhound","Mistral Minion","Spellbound Golem"],
        "forbidden_portal": ["Fear Frog","Terror Toad","Aberrant Chacma","Barhide Menace","All-Seeing Eye","Bearded Pupowl","Blushing Tangle","Calico Ferberus","Ferberus","Deeprealm Leon","Medusa Leon","Everburn Tangle","Foolish Prince","Mindless Flight","Frogspawn Flyer","Giggling Planesrunner","Teleporting Planesrunner","Lap Pupowl","Portal Watcher","Sanguine Multimist","Sparksylph","Spectre Wyvern","Springfoot Bilworper","Tattertail Bilworper","Starspawn Flyer"]
    };

})();












